// src/components/Footer.vue
<template>
    <!-- Site footer with copyright information -->
    <footer
        class="mt-8 border z-10 border-t-[#33353F] border-l-transparent border-r-transparent text-white"
    >
        <div class="container p-12 flex flex-col md:flex-row justify-between items-center">
            <!-- Site brand/logo -->
            <div class="text-white text-3xl font-bold mb-4 md:mb-0">Dihan Britz</div>

            <!-- Copyright and license information -->
            <div class="text-slate-600 text-center md:text-right">
                <p>© 2025 Dihan Britz</p>
                <p class="text-sm">
                    <a href="https://github.com/DoubledDoge/personal-website/blob/main/LICENSE" target="_blank" rel="noopener noreferrer" class="hover:text-white">
                        Open source under MIT License
                    </a>
                </p>
            </div>
        </div>
    </footer>
</template>

<script setup lang="ts">
/**
 * Site Footer Component
 *
 * A simple footer that displays the site branding, copyright information,
 * and license details. Responsive layout that adapts to different screen sizes.
 */

// Define component name for debugging and DevTools
defineOptions({
    name: 'SiteFooter'
});
</script>

// src/components/Footer.svelte
<script lang="ts">
    import '$styles/components/footer.scss'

    interface SiteInfo {
        name: string
        githubRepo: string
        licenseUrl: string
    }

    let currentYear: number = $state(new Date().getFullYear())

    let siteInfo: SiteInfo = $state({
        name: 'Dihan Britz',
        githubRepo: 'https://github.com/DoubledDoge/personal-website',
        licenseUrl: 'https://github.com/DoubledDoge/personal-website/blob/main/LICENSE',
    })

    $effect((): (() => void) => {
        const interval: ReturnType<typeof setInterval> = setInterval((): void => {
            const newYear: number = new Date().getFullYear()
            if (newYear !== currentYear) {
                currentYear = newYear
            }
        }, 604800000)

        return (): void => clearInterval(interval)
    })
</script>

<footer aria-label="Site footer" class="footer-container">
    <div class="footer-content">
        <div class="footer-brand-section">
            <h2 class="footer-brand-title">
                {siteInfo.name}
            </h2>
        </div>

        <div class="footer-info-section">
            <p class="footer-copyright">
                © {currentYear}
                {siteInfo.name}
            </p>

            <p class="footer-license-text">
                <a
                        aria-label="View MIT License on GitHub (opens in new tab)"
                        class="footer-license-link"
                        href={siteInfo.licenseUrl}
                        rel="noopener noreferrer"
                        target="_blank"
                >
                    Open source under MIT License

                    <svg
                            aria-hidden="true"
                            class="footer-external-icon"
                            height="14"
                            stroke="currentColor"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            viewBox="0 0 24 24"
                            width="14"
                    >
                        <path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>
                        <polyline points="15,3 21,3 21,9"/>
                        <line x1="10" x2="21" y1="14" y2="3"/>
                    </svg>
                </a>
            </p>
        </div>
    </div>
</footer>
